# Generated by Django 4.1.4 on 2023-07-15 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devedu", "0002_alter_course_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial", models.IntegerField(null=True)),
                ("file", models.FileField(null=True, upload_to="")),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devedu.course",
                    ),
                ),
            ],
        ),
    ]
