# Generated by Django 4.1.4 on 2023-07-17 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devedu", "0004_coursecontent_title_alter_course_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecontent",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="devedu.course",
            ),
        ),
    ]
