# Generated by Django 4.1.4 on 2023-07-24 12:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("devedu", "0005_alter_coursecontent_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(default="", editable=False),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(3000)]
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_pic", models.ImageField(blank=True, upload_to="profilePics")),
                (
                    "about",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
                ("is_instructor", models.BooleanField(blank=True, default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to="devedu.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="course",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="devedu.instructor",
            ),
        ),
    ]
