# Generated by Django 4.1.4 on 2023-07-24 12:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("devedu", "0006_course_slug_alter_course_description_userprofile_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="user",),
        migrations.RemoveField(model_name="course", name="slug",),
        migrations.AlterField(
            model_name="course",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(500)]
            ),
        ),
        migrations.DeleteModel(name="Instructor",),
        migrations.DeleteModel(name="UserProfile",),
    ]
