# Generated by Django 4.1.4 on 2023-07-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devedu", "0008_course_slug_alter_course_description_userprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
