# Generated by Django 4.1.4 on 2023-07-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devedu", "0010_alter_course_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecontent",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instructor",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
