# Generated by Django 4.1.4 on 2023-07-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devedu", "0011_coursecontent_is_free_instructor_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="github",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="linkedin",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mail",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
