# Generated by Django 4.1.4 on 2023-07-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devedu", "0013_userprofile_first_name_userprofile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
