# Generated by Django 4.1.4 on 2023-07-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devedu", "0014_alter_course_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="instructor", name="resume",),
        migrations.AddField(
            model_name="course",
            name="enrolled_students",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="devedu.userprofile"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="applied",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="course",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="devedu.instructor",
            ),
        ),
    ]
