# Generated by Django 4.1.4 on 2023-08-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devedu", "0016_review_course_git_repository_reviewcoursemiddle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="created_on",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reviewcoursemiddle",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="devedu.course",
            ),
        ),
    ]
