# Generated by Django 4.1.4 on 2023-08-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devedu", "0019_review_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="avg_rating",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
