# Generated by Django 4.1.4 on 2023-08-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devedu", "0020_course_avg_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name="course", name="discord", field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="course", name="quiz", field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="tags",
            field=models.ManyToManyField(to="devedu.tag"),
        ),
    ]
